from tkinter import *
import tkinter
root1 = Tk()
frame1 = Frame(root1)
frame1.pack()
bottomframe1 = Frame(root1)
bottomframe1.pack( side = BOTTOM )
redbutton1 = Button(frame1, text="Red", fg="red")
redbutton1.pack( side = LEFT)
greenbutton1 = Button(frame1, text="Brown", fg="brown")
greenbutton1.pack( side = LEFT )
bluebutton1 = Button(frame1, text="Blue", fg="blue")
bluebutton1.pack( side = LEFT )
blackbutton1 = Button(bottomframe1, text="Black", fg="black")
blackbutton1.pack( side = BOTTOM)
yellowbutton1 = Button(bottomframe1, text="Yellow", fg="yellow", bg="red")
yellowbutton1.pack( side = RIGHT)
greenbutton1 = Button(bottomframe1, text="Green", fg="green")
greenbutton1.pack( side = RIGHT)
violetbutton1 = Button(bottomframe1, text="Violet", fg="violet")
violetbutton1.pack( side = LEFT)
pinkbutton1 = Button(bottomframe1, text="Pink", fg="pink")
pinkbutton1.pack( side = BOTTOM)
root1.mainloop()